apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  targetNamespace: cert-manager
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  interval: 5m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    installCRDs: true
    nodeSelector:
      "kubernetes.io/os": linux
    webhook:
      hostNetwork: true
      securePort: 10260
      nodeSelector:
        "kubernetes.io/os": linux 
    cainjector:
      nodeSelector:
        "kubernetes.io/os": linux
    startupapicheck:
      nodeSelector:
        "kubernetes.io/os": linux