apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${cert_manager_namespace}
resources:
  - trusted-certs
  - repository.yaml
  - cert-manager.yaml
  - trust-manager.yaml
  - networkpolicy.yaml