apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: ${trustmanager_namespace}
spec:
  targetNamespace: ${trustmanager_namespace}
  releaseName: trust-manager
  chart:
    spec:
      chart: trust-manager
      version: ${trustmanager_chart_version}
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: ${trustmanager_namespace}
  interval: 5m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  dependsOn:
    - name: cert-manager
      namespace: ${cert_manager_namespace}