apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${certmanager_namespace}
configMapGenerator:
  - name: nhs-certificates
    files:
      - root-nwsis-ca.crt=ROOT-NWSIS-CA.crt
      - sub-lth-ca=SUB-LTH-CA.crt
generatorOptions:
  disableNameSuffixHash: true
